name: inspector
description: A Flutter package for inspecting widgets. Useful for quick debugging or QA testing.
version: 2.1.0
homepage: https://github.com/kekland/inspector

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ^3.16.0

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  archive: ^3.3.7
  bloc: ^8.1.2
  collection: ^1.17.1
  cuberto_bottom_bar: ^2.0.0
  cupertino_icons: ^1.0.2
  desktop_multi_window: ^0.2.0
  dio: ^5.3.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_json_view: ^1.1.2
  font_awesome_flutter: ^10.5.0
  http: ^1.1.0
  menu_bar: ^0.5.3
  meta: ^1.9.1
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.1.0
  rxdart: ^0.27.7
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  envied_generator: ^0.5.2
  mobx_codegen: ^2.6.0+1
  flutter_gen_runner: ^5.3.2
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
